unique_ids:
  assets:
    standard-page.html: PBPQMQDDEWQKDQK4DRGRAIP2ZERBRJBQ
    theme.css: HWERQYMOV7FNGPDQMWTDKV2C5BUJ77QF
  forms:
    Form1: SV5S2J6JZSFTS4CJ3ELMLHVB7BSNIP4Q
  modules: {}
  scripts: {}
  server_modules: {}
